version: "3.9"
name: fastapidev

services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./.env
    ports:
      - "5434:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
